# Producción: variables de entorno inyectadas por Railway / Docker
spring.datasource.url=postgresql://postgres:qpDuXmTdakBeMVZsAkEeUklcjaEazjcQ@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=qpDuXmTdakBeMVZsAkEeUklcjaEazjcQ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=WARN
logging.level.com.universidad=INFO

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized